GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/info

###

GET http://localhost:3001/api/notes/635fec0bed571fc56118b7ef

###

GET http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431

###

GET http://localhost:3001/api/notes/3

###

DELETE http://localhost:3001/api/notes/635c2291b0da515e48a2edcb

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Hello is this is larger than 5?",
    "important": true
}